# Jekyll Resume Theme

# Site settings
title: Carlos' Resume 
email: carlosfilho92@gmail.com
description: Just my resume 
baseurl: "/resume
author: 'Carlos Filho'
url: ""

name: Carlos

# Build settings
markdown: kramdown
